"""FAQ page."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))  # project root, so `app.utils` imports work
import streamlit as st

from app.utils.app_state import footer, get_data, get_model, setup_page

setup_page("FAQ")
df = get_data()
model = get_model()

st.title("❓ Frequently asked questions")

with st.expander("How does the estimator work?", expanded=True):
    st.write("An XGBoost regression model, tuned with Optuna, learns how weekly rent relates to bedrooms, "
             "property type and suburb characteristics such as household income, SEIFA advantage score, "
             "employment, Year 12 completion, distance to the CBD and recent house price growth.")
with st.expander("How accurate is it?"):
    st.write(f"On rent records the model never saw during training, its average error is about "
             f"${model.test_mae:,.0f} per week and it explains {model.test_r2:.0%} of the variation in rent. "
             "Treat the estimate as a guide, not a quote.")
with st.expander("Is it equally accurate for every suburb?"):
    st.write("No. Our fairness audit found errors are smallest in lower income suburbs and largest in the most "
             "affluent suburbs, where the model tends to underestimate rent. Estimates for very high income "
             "areas should be read with extra care.")
with st.expander("Which suburbs and homes are covered?"):
    st.write(f"{df['suburb'].nunique()} Victorian suburbs. Homes from 1 to 4 bedrooms, where 1 bedroom homes are "
             "only published as flats and 4 bedroom homes only as houses.")
with st.expander("What is the 'Why this price?' chart?"):
    st.write("It uses SHAP, a standard method that splits one prediction into how much each factor moved it up "
             "or down from the model's average starting point. The written explanation is generated by an AI "
             "model using only those numbers. The AI does not make the prediction.")
with st.expander("Can I rely on this for a lease decision?"):
    st.write("It is a university prototype for understanding market trends. Check current listings and speak "
             "to an agent before making decisions.")

footer()
